### ISSUE TITLE
Wiki 개발환경 설정 문서 추가 요청

### ISSUE THREAD

**Issue by silverprize** [Pyohwan/JakduK#6]
PR하고 싶은데 작두K 개발환경 설정을 어떻게 해야될지 모르겠어요.
개발 환경설정 문서가 있으면 좋을 것 같습니다.
가급적 인텔리J면 좋을 것 같습니다. 
이클립스 기준이라도 큰 도움이 될 것 같습니다.

**Comment by Pyohwan** [comment]
조만간 인텔리J 라이센스를 잃게 될것이라 인텔리J로는 현재 힘들고 이클립스 환경에서 작두왕을 구동하는 법을 문서화 하도록 하겠습니다. 향후 인텔리J를 사용할 수 있게 된다면 추가해볼께요.

**Comment by silverprize** [comment]
2016년을 맞이하여 https://www.jetbrains.com/store/#section=personal 지르심이?
1년 이용료를 지불하고 1년이 지나면 영구 라이센스로 전환되고 패치 서비스는 받을 수 있습니다.
추후 메이저 업데이트를 이용하고 싶을때 다시 지불하면 됩니다.

**Comment by Pyohwan** [comment]
149 달러라.. 고민이 많아지는 가격이군요.

**Comment by Pyohwan** [comment]
https://github.com/Pyohwan/JakduK/wiki/Localhost%EC%97%90-%EA%B0%9C%EB%B0%9C-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%B6%95

위키 문서 추가.

**Comment by silverprize** [comment]
이클립스 패키지는 **Eclipse IDE for Java EE Developers** 맞나요?

**Comment by Pyohwan** [comment]
네 맞습니다.

**Comment by silverprize** [comment]
https://github.com/Pyohwan/JakduK/wiki/Localhost%EC%97%90-%EA%B0%9C%EB%B0%9C-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%B6%95#localhost%EC%97%90-%EB%A7%9E%EB%8A%94-jakduk-%EC%84%A4%EC%A0%95
/jakduk-web/resources-local폴더가 없는데요?

**Comment by Pyohwan** [comment]
https://github.com/Pyohwan/JakduK/tree/master/jakduk-web/resources-local

**Comment by silverprize** [comment]
아하

**Comment by silverprize** [comment]
![2015-12-17 1 11 20](https://cloud.githubusercontent.com/assets/860087/11861066/b090db9c-a4bf-11e5-953f-2cd69f249121.png)
살려주셈

**Comment by Pyohwan** [comment]
메이븐으로 jar를 하나도 못가져온것 같은데요. jakduk-web 프로젝트의 Properties를 열고, Deployment Assembly가 아래의 그림처럼 나오는지 확인 바랍니다.

![image](https://cloud.githubusercontent.com/assets/1825642/11861117/44108480-a4c0-11e5-9af8-3721793f7c15.png)

**Comment by silverprize** [comment]
jest 0.1.7이 이상한데요?
https://github.com/searchbox-io/Jest/tree/jest-parent-0.1.7/jest
io.searchbox.client.JestClient라는 클래스는 없어요

![2015-12-17 1 32 25](https://cloud.githubusercontent.com/assets/860087/11861354/a892c3a8-a4c2-11e5-873c-3a6e1a02f930.png)

**Comment by silverprize** [comment]
jest를 통해서 jest-common이 들어와야 되나본데 안들어와요

**Comment by Pyohwan** [comment]
Jakduk-common 프로젝트의 Maven Dependencies 목록에서 jest-common-0.1.7.jar가 있는지 확인해 주세요. 원래 jest-0.1.7.jar를 가져올 때 종속되어 있는 jest-common도 함께 가져와야 정상입니다.
만일 jest-common-.0.1.7.jar 에 대한 dependency를 jakduk-parent의 pom.xml에 추가해 주세요.
```
<dependency>
	<groupId>io.searchbox</groupId>
	<artifactId>jest-common</artifactId>
	<version>0.1.7</version>
</dependency>
```
![image](https://cloud.githubusercontent.com/assets/1825642/11861472/04e15790-a4c4-11e5-8860-3cdc7c0478e8.png)

**Comment by silverprize** [comment]
eclipse mars 1 release
maven 3.3.9
~/.m2에 아티팩트 다 받아놓고 이클립스에서 프로젝트 임포트하니까 되네요
메이븐 플러그인이 썩은 것 같아요
이클립스로 안할래요

**Comment by silverprize** [comment]
이건 무슨 상황입니까
```
[ INFO] [localhost-startStop-1 14:27:19] (SpringSecurityCoreVersion.java:performVersionChecks:59) You are running with Spring Security Core 4.0.2.RELEASE
[ INFO] [localhost-startStop-1 14:27:19] (SecurityNamespaceHandler.java:<init>:78) Spring Security 'config' module version is 4.0.2.RELEASE
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'isAnonymous()' for /login*
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'isAnonymous()' for /j_spring_*
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'isAnonymous()' for /user/write
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'authenticated' for /user/**
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'authenticated' for /oauth/callback
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'authenticated' for /oauth/**
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'permitAll' for /check/**
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'hasAnyRole('ROLE_USER_01', 'ROLE_USER_02', 'ROLE_USER_03')' for /board/*/write
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'hasRole('ROLE_ROOT')' for /admin/**
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'permitAll' for /logout
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'permitAll' for /home
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'permitAll' for /about
[ INFO] [localhost-startStop-1 14:27:19] (FilterInvocationSecurityMetadataSourceParser.java:parseInterceptUrlsForFilterInvocationRequestMap:158) Creating access control expression attribute 'hasRole('ROLE_ROOT')' for /sample
[ INFO] [localhost-startStop-1 14:27:19] (HttpSecurityBeanDefinitionParser.java:checkFilterChainOrder:306) Checking sorted filter chain: [Root bean: class [org.springframework.security.web.access.channel.ChannelProcessingFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 100, Root bean: class [org.springframework.security.web.context.SecurityContextPersistenceFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 200, Root bean: class [org.springframework.security.web.session.ConcurrentSessionFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 300, Root bean: class [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 400, Root bean: class [org.springframework.security.web.header.HeaderWriterFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 500, Root bean: class [org.springframework.security.web.authentication.logout.LogoutFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 700, <org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0>, order = 1100, Root bean: class [org.springframework.security.web.authentication.www.BasicAuthenticationFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1500, Root bean: class [org.springframework.security.web.savedrequest.RequestCacheAwareFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1600, Root bean: class [org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1700, Root bean: class [org.springframework.security.web.authentication.AnonymousAuthenticationFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2000, Root bean: class [org.springframework.security.web.session.SessionManagementFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2100, Root bean: class [org.springframework.security.web.access.ExceptionTranslationFilter]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2200, <oauth2ClientFilter>, order = 2201, <oauthFilter>, order = 2299, <org.springframework.security.web.access.intercept.FilterSecurityInterceptor#0>, order = 2300]
[ WARN] [localhost-startStop-1 14:27:21] (AbstractApplicationContext.java:refresh:544) Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'boardDAO': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.jakduk.dao.JongoR com.jakduk.dao.BoardDAO.jongoR; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.jakduk.dao.JongoR] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:835)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.jakduk.dao.JongoR com.jakduk.dao.BoardDAO.jongoR; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.jakduk.dao.JongoR] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 22 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.jakduk.dao.JongoR] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
	... 24 more
[ERROR] [localhost-startStop-1 14:27:21] (ContextLoader.java:initWebApplicationContext:353) Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'boardDAO': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.jakduk.dao.JongoR com.jakduk.dao.BoardDAO.jongoR; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.jakduk.dao.JongoR] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:835)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.jakduk.dao.JongoR com.jakduk.dao.BoardDAO.jongoR; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.jakduk.dao.JongoR] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 22 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.jakduk.dao.JongoR] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
	... 24 more
12월 17, 2015 2:27:21 오후 org.apache.catalina.core.StandardContext listenerStart
심각: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'boardDAO': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.jakduk.dao.JongoR com.jakduk.dao.BoardDAO.jongoR; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.jakduk.dao.JongoR] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:835)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.jakduk.dao.JongoR com.jakduk.dao.BoardDAO.jongoR; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.jakduk.dao.JongoR] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:571)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 22 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.jakduk.dao.JongoR] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:543)
	... 24 more

12월 17, 2015 2:27:21 오후 org.apache.catalina.core.StandardContext startInternal
심각: One or more listeners failed to start. Full details will be found in the appropriate container log file
12월 17, 2015 2:27:21 오후 org.apache.catalina.core.StandardContext startInternal
심각: Context [/jakduk-web] startup failed due to previous errors
12월 17, 2015 2:27:21 오후 org.apache.catalina.core.ApplicationContext log
정보: Closing Spring root WebApplicationContext
12월 17, 2015 2:27:21 오후 org.apache.coyote.AbstractProtocol start
정보: Starting ProtocolHandler ["http-nio-8080"]
12월 17, 2015 2:27:21 오후 org.apache.coyote.AbstractProtocol start
정보: Starting ProtocolHandler ["ajp-nio-8009"]
12월 17, 2015 2:27:21 오후 org.apache.catalina.startup.Catalina start
정보: Server startup in 10004 ms
```

**Comment by Pyohwan** [comment]
아 이거는 지금 테스트 중인 소스가 trunk에 올라가 있어서 안되는겁니다. 되는걸로 급하게 커밋할께요.

**Comment by Pyohwan** [comment]
소스 업데이트 하고 다시 수행해보세요.

**Comment by silverprize** [comment]
이클립스 + 메이븐 조합은 막장이라는 것을 다시금 확인했습니다.

![2015-12-17 2 55 30](https://cloud.githubusercontent.com/assets/860087/11862415/40a02ef0-a4ce-11e5-8613-074c4acc0652.png)

**Comment by silverprize** [comment]
이클립스로 환경설정 완료까지
1. 레포지토리 클론
2. 로컬 레포지토리로 가서 mvn install 입력 (디펜던시 아피택트 다운로드가 목적)
3. 이클립스 실행 import -> maven -> exsisting maven projects
4. [Servers -> jakduk-web 추가](https://github.com/Pyohwan/JakduK/wiki/Localhost%EC%97%90-%EA%B0%9C%EB%B0%9C-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%B6%95#ecpipse%EC%97%90%EC%84%9C-tomcat-%EC%97%B0%EB%8F%99)
5. 실행 성공

**Comment by Pyohwan** [comment]
고생 많으셨네요. OS X에서 작업 하셨죠? 리눅스에서는 잘 되던데 아무튼 이클립스가 참 손이 많이 가긴 합니다.
인텔리제이 구매는 고민중입니다.

**Comment by Pyohwan** [comment]
IntelliJ IDEA에서 JakduK 설정하는 방법을 wiki에 올렸습니다. 역시나 이클립스보다는 훨씬 좋군요.

https://github.com/Pyohwan/JakduK/wiki/Localhost%EC%97%90-%EA%B0%9C%EB%B0%9C-%ED%99%98%EA%B2%BD-%EA%B5%AC%EC%B6%95%28IntelliJ-IDEA%29
